#
# PX4 ROS development environment
#

FROM px4io/px4-dev-simulation
MAINTAINER Daniel Agar <daniel@agar.ca>

RUN apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116 \
	&& sh -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list' \
	&& sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu/ xenial main" > /etc/apt/sources.list.d/ros-shadow.list' \
	&& apt-get update \
	&& apt-get -y --quiet --no-install-recommends install \
		python-tk \
		ros-kinetic-gazebo-ros-pkgs \
		ros-kinetic-mavros \
		ros-kinetic-mavros-extras \
		ros-kinetic-ros-base \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	# pip
	&& pip install matplotlib numpy \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# TODO: wget https://raw.githubusercontent.com/mavlink/mavros/master/mavros/scripts/install_geographiclib_datasets.sh
# sudo bash install_geographiclib_datasets.sh

RUN rosdep init && rosdep update
